### ISSUE TITLE
 BUG (and fix?) - "isses" from lang.conjugations.it

### ISSUE THREAD

**Issue by KVonGit** [ThePix/QuestJS#45] opened 2020-12-18 02:48 UTC
Hello.

I was getting "The TV isses not a container."

I found the bit of code:
https://github.com/ThePix/QuestJS/blob/8939148f7c2c3e63665246dc263493b724845cf2/lang/lang-en.js#L683

I added this second line:

```js
      { name:"be", value:"is"},
      { name:"is", value:"is"},
```

**Comment by ThePix** [comment] 2020-12-18 07:34
The issue is that it was not using the infinitive (is rather than be).
Now fixed, thanks.

**Closed by ThePix** 2020-12-18 07:34 UTC
